export const authErrorCodes = {
    USERNAME_MIN: 'USERNAME_MIN',
    PASSWORD_MIN: 'PASSWORD_MIN',
    USERNAME_TAKEN: 'USERNAME_TAKEN',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    REQUIRED_FIELDS: 'REQUIRED_FIELDS',
    SERVER_ERROR: 'SERVER_ERROR',
} as const
