export const resultsViewConfig = {
  icons: {
    wpm: '⚡',
    runAgain: '↻',
    settings: '⚙',
    history: '📊',
  },
  format: {
    timeDecimals: 1,
    accuracyDecimals: 0,
    wpmDecimals: 0,
  },
  tooltip: {
    offsetX: 12,
    offsetY: -18,
    paddingX: 10,
    paddingY: 6,
    radius: 'rounded-full',
    maxWidthClass: 'max-w-[160px]',
    opacityClass: 'bg-opacity-90',
  },
  chart: {
    width: 100,
    height: 36,
    paddingX: 6,
    paddingY: 6,
    gridLines: 4,
    gridOpacity: 0.08,
    gridStrokeWidth: 0.4,
    lineWidth: 1.4,
    dotRadius: 1.4,
    glowOpacity: 0.6,
    glowWidthMultiplier: 2.4,
    fillOpacity: 0.12,
    dotDelayStep: 0.02,
    gradientStops: {
      start: 0.4,
      mid: 1,
      end: 0.5,
    },
  },
  series: {
    points: 14,
    startFactor: 0.55,
    endFactor: 1.05,
    waveAmplitude: 0.08,
    waveFrequency: 2.4,
    minValue: 1,
  },
  animation: {
    containerYOffset: 18,
    containerDuration: 0.5,
    ease: 'easeOut',
    wpmDelay: 0.1,
    perfectDelay: 0.25,
    accuracyDelay: 0.35,
    chartDelay: 0.45,
    summaryDelay: 0.6,
    actionsDelay: 0.75,
    buttonHoverScale: 1.04,
    buttonTapScale: 0.97,
  },
  overlay: {
    delayMs: 220,
    backdropOpacity: 0.65,
    backdropDuration: 0.35,
    panelDuration: 0.45,
    panelScale: 0.96,
    panelYOffset: 20,
    ease: 'easeOut',
    zIndexClass: 'z-40',
  },
}
