import type { LanguageCode } from '../types'

export const textGeneratorConfig: Record<LanguageCode, {
  syllables: string[]
  endings: string[]
  quotes: string[]
}> = {
  ru: {
    syllables: [
      'ба', 'бе', 'би', 'бо', 'бу', 'бы', 'бь',
      'ва', 'ве', 'ви', 'во', 'ву', 'вы', 'вь',
      'га', 'ге', 'ги', 'го', 'гу', 'гы',
      'да', 'де', 'ди', 'до', 'ду', 'ды', 'дь',
      'жа', 'же', 'жи', 'жо', 'жу', 'жи',
      'за', 'зе', 'зи', 'зо', 'зу', 'зы', 'зь',
      'ка', 'ке', 'ки', 'ко', 'ку', 'кы',
      'ла', 'ле', 'ли', 'ло', 'лу', 'лы', 'ль',
      'ма', 'ме', 'ми', 'мо', 'му', 'мы', 'мь',
      'на', 'не', 'ни', 'но', 'ну', 'ны', 'нь',
      'па', 'пе', 'пи', 'по', 'пу', 'пы', 'пь',
      'ра', 'ре', 'ри', 'ро', 'ру', 'ры', 'рь',
      'са', 'се', 'си', 'со', 'су', 'сы', 'сь',
      'та', 'те', 'ти', 'то', 'ту', 'ты', 'ть',
      'фа', 'фе', 'фи', 'фо', 'фу', 'фы',
      'ха', 'хе', 'хи', 'хо', 'ху', 'хы',
      'ца', 'це', 'ци', 'цо', 'цу', 'цы',
      'ча', 'че', 'чи', 'чо', 'чу',
      'ша', 'ше', 'ши', 'шо', 'шу',
      'ща', 'ще', 'щи', 'що', 'щу',
      'я', 'е', 'ё', 'ю', 'и', 'а', 'о', 'у', 'ы', 'э',
    ],
    endings: ['а', 'е', 'и', 'о', 'у', 'ы', 'я', 'ь', 'й'],
    quotes: [
      'Программирование — это искусство решения проблем с помощью кода.',
      'Хороший код читается как хорошо написанная книга.',
      'Преждевременная оптимизация — корень всех зол.',
      'Лучший способ отладить код — это написать его правильно с первого раза.',
      'Код пишется один раз, но читается тысячи раз.',
      'Простота — это высшая форма изысканности.',
      'Не повторяй себя — это основа хорошей архитектуры.',
      'Тестирование показывает наличие багов, а не их отсутствие.',
      'Чистый код — это не код, который компилируется, а код, который понятен.',
      'Лучший код — это код, который не нужно писать.',
      'Программист — это человек, который превращает кофе в код.',
      'Отладка в два раза сложнее написания кода.',
      'Измеряй дважды, режь один раз — это относится и к программированию.',
      'Любой дурак может написать код, понятный компьютеру. Хорошие программисты пишут код, понятный людям.',
      'Первое правило оптимизации: не оптимизируй. Второе правило: не оптимизируй пока.',
      'Программирование — это не о том, чтобы знать все, а о том, чтобы знать, где искать.',
      'Код без тестов — это легаси код, даже если он написан вчера.',
      'Единственный способ научиться программированию — это программировать.',
      'Хороший программист смотрит в обе стороны, переходя одностороннюю улицу.',
      'Программирование — это навык, приобретаемый практикой, а не наблюдением.',
    ],
  },
  en: {
    syllables: [
      'ba', 'be', 'bi', 'bo', 'bu',
      'ca', 'ce', 'ci', 'co', 'cu',
      'da', 'de', 'di', 'do', 'du',
      'fa', 'fe', 'fi', 'fo', 'fu',
      'ga', 'ge', 'gi', 'go', 'gu',
      'ha', 'he', 'hi', 'ho', 'hu',
      'la', 'le', 'li', 'lo', 'lu',
      'ma', 'me', 'mi', 'mo', 'mu',
      'na', 'ne', 'ni', 'no', 'nu',
      'pa', 'pe', 'pi', 'po', 'pu',
      'ra', 're', 'ri', 'ro', 'ru',
      'sa', 'se', 'si', 'so', 'su',
      'ta', 'te', 'ti', 'to', 'tu',
      'cla', 'cre', 'pro', 'tri', 'pla',
      'sha', 'she', 'shi', 'cha', 'che',
      'thr', 'str', 'spr', 'spl', 'gl',
    ],
    endings: ['a', 'e', 'i', 'o', 'u', 'n', 'r', 's', 't', 'd', 'ly', 'er', 'ing'],
    quotes: [
      'Programming is the art of solving problems with code.',
      'Good code reads like a well-written book.',
      'Premature optimization is the root of all evil.',
      'The best way to debug is to write it right the first time.',
      'Code is written once but read thousands of times.',
      'Simplicity is the ultimate sophistication.',
      'Don’t repeat yourself — it’s the core of good architecture.',
      'Testing shows the presence of bugs, not their absence.',
      'Clean code is not code that compiles — it is code that is understood.',
      'The best code is code you don’t have to write.',
      'A programmer is someone who turns coffee into code.',
      'Debugging is twice as hard as writing the code in the first place.',
      'Measure twice, cut once — it applies to programming too.',
      'Any fool can write code a computer understands. Good programmers write code humans understand.',
      'First rule of optimization: don’t. Second rule: don’t yet.',
      'Programming is not about knowing everything; it’s about knowing where to look.',
      'Code without tests is legacy code, even if it was written yesterday.',
      'The only way to learn programming is to program.',
      'A good programmer looks both ways before crossing a one-way street.',
      'Programming is a skill earned by practice, not by watching.',
    ],
  },
}
